### ISSUE TITLE
User-agent how to use it

### ISSUE THREAD

**Issue by robertopaixaodev** [s-ted/liPng#10]
I have problems downloading user games, every time I download it, it sends this message "Lichess is rate-limiting us, waiting 120 seconds", and I know that the User-agent has been made available, but I have no idea how to configure it, if I should write something in the .bat file or edit some file, can the program creator help me please?

**Comment by s-ted** [comment]
Hi,
to use the "custom User-agent", you can simply add `--user-agent lipgn-robertobrunopl` on the command line, such as : 
`java -jar liPGN.jar -u Fins --variant standard --speed classical,blitz --user-agent lipgn-robertobrunopl`

There is no `.bat` file in this project, but if you made one (on Windows for example), it would be exactly the place to put the `--user-agent lipgn-robertobrunopl` in, just at the same place as the other `java -jar liPGN.jar ...` options. On mac / linux it would be the `liPGN.sh` file.

After checking with a lichess admin, they are eventually enforcing a rate limit on the API by user agent. He specifically told me that he was using liPGN using the --user-agent option with a custom value of it's own.

It is to be noted that, even with a custom user-agent, lichess API will still send some 429 response status (which is seen by the "Lichess is rate-limiting us, waiting 120 seconds" message), it is simply lichess way of saying that too much people needs access to the API and that it is currently giving the priority to some other than you... but it should not impact the import other than taking much more time...

**Comment by robertopaixaodev** [comment]
Is there any way to avoid waiting for those multiple 120 seconds on Lipgn and download faster?
Thanks for the response, keep being a great programmer and a nice person.

**Comment by robertopaixaodev** [comment]
Anyway, This one can be closed for sure, thanks
