### ISSUE TITLE
Something changed from a program that was perfect for me

### ISSUE THREAD

**Issue by robertopaixaodev** [s-ted/liPng#11]
Until 4 months ago, Lipgn works perfectly for me, now when I run the program there will appear some strange messages in the middle and then it goes into some kind of infinite loop of the following message: "Lichess is rate-limiting us, waiting 120s ... "

Here is an example of some strange messages:
----------------------------------------------------------------------------------------------------------
C: \ Users \ x \ Desktop \ x> java -jar liPGN.jar -u robertobrunopl -c black
Picked up _JAVA_OPTIONS: -Xverify: none
WARNING: seqable? already refers to: # 'clojure.core / seqable? in namespace: clojure.core.incubator, being replaced by: # 'clojure.core.incubator / seqable?
WARNING: seqable? already refers to: # 'clojure.core / seqable? in namespace: clostache.parser, being replaced by: # 'clojure.core.incubator / seqable?
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.orientechnologies.common.directmemory.OByteBufferPool (file: / C: /Users/x/Desktop/x/liPGN.jar) to method sun.nio.ch.DirectBuffer.cleaner ()
WARNING: Please consider reporting this to the maintainers of com.orientechnologies.common.directmemory.OByteBufferPool
WARNING: Use --illegal-access = warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
-------------------------------------------------- -------------------------------------------------- ------

I dont have the slightest idea what this message means, but below the program continued normally and then I didnt question anything, but then an infinite loop of the message "Lichess is rate-limiting us, waiting 120s ..." and never download any page or anything. : 

-------------------------------------------------------------------------------------------------------
[34mUpdating user robertobrunopl from server.
? [0m? [34mRetrieving user robertobrunopl games from server since day one.
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
? [0m? [36mLichess is rate-limiting us, waiting 120s ...
--------------------------------------------------------------------------------------------------------
Yes I'm new in programming and using this stuff on windows, probably I should be making some kind of mistake, but most people who use your program should also be new and use windows, please god Sylvain Tedoldi saves us. Tell us a method of opening this using an .bat file without errors

**Comment by s-ted** [comment]
Most of the lines are (just) Warnings... that can be safly ignored (this is due to the Java 9 upgrade).

But you are correct on the fact that nothing get downloaded because of the instantly appearing "Lichess is rate-limiting us, waiting 120s ..." message !
Testing on my device do exactly the same thing !

Having check with Thibault (lichess main dev) :
> "that API is still supported but it's being hammered so hard, it has hit the global rate limit :("

this means that liPGN will never work again as-is...

But Thibault also give you a new way of doing it, directly via the lichess API (thus without having to use liPGN) : https://lichess.org/api#operation/gamesExportUsername


This new API simply means that liPGN is not needed anymore ! and that anyone can use it on it's own to retrieve directly a PGN formatted file.

**Comment by robertopaixaodev** [comment]
Okay sir, thank you so much for creating liPGN and thanks for the API tip, may the force be with you!
